name: "Setops deployment"
description: "Creates and activates releases for multiple apps within a SetOps stage, performs a predeploy command, waits for the releases to become healthy"

inputs:
  setops-organization:
    description: The SetOps organization
    required: false
  setops-project:
    description: The SetOps project name
    required: true
  setops-username:
    description: The SetOps username, usually obtained via secrets.SETOPS_USER
    required: true
  setops-password:
    description: The SetOps password, usually obtained via secrets.SETOPS_PASSWORD
    required: true
  image-digest:
    description: The image digest that was returned when pushing the image to the SetOps registry
    required: true
  setops-stage:
    description: The setops stage for the deployment, e.g. production
    required: true
  setops-apps:
    description: The SetOps apps to deploy, space separated, e.g. "app1 app2 app3"
    required: true
  number-of-retries-to-wait-for-successful-deployment:
    description: Max. number of times to wait for a succesful deployment (we sleep for 5 seconds between tries, so 12 equals 1 minute)
    required: false
    default: "24"
  predeploy-command:
    description: A predeploy command to be run before activating the releases, e.g. for migrating the database
    required: false
runs:
  using: "composite"
  steps:
    - name: "Install Setops"
      uses: setopsco/setup-setops@v3
      with:
        setops_organization: ${{ inputs.setops-organization }}
        setops_username: ${{ inputs.setops-username }}
        setops_password: ${{ inputs.setops-password }}
    - name: "Setops deployment"
      run: |
        shopt -s expand_aliases
        alias sos='setops -p ${{ inputs.setops-project }} -s ${{ inputs.setops-stage }}'

        sos changeset:discard || true

        read -r -a apps <<< "${{ inputs.setops-apps }}"

        declare -A apps_with_release_id
        for app in "${apps[@]}"; do
          apps_with_release_id[$app]=$(sos --app "$app" release:create ${{ inputs.image-digest }} | grep -o 'ReleaseID.*' | grep -o '[0-9].*')
        done

        echo "Changeset for creating releases"
        sos changeset:commit

        predeploy_command="${{ inputs.predeploy-command }}"
        if [ ${#predeploy_command} -gt 0 ]; then
          echo "Run predeploy command"
          first_app=${apps[0]}
          release_id_of_first_app=${apps_with_release_id[$first_app]}
          sos --app "$first_app" task:run --debug --release "$release_id_of_first_app" -- bash -c "${{ inputs.predeploy-command }} && echo 'SETOPS_SUCCESS'" | tee /dev/stderr | grep "SETOPS_SUCCESS" > /dev/null
        else
          echo "No predeploy command has been configured, skipping."
        fi

        for app in "${apps[@]}"; do
          release_id=${apps_with_release_id[$app]}
          sos --app "$app" release:activate "$release_id"
        done

        echo "Changeset for activating releases"
        sos changeset:commit

        echo "Waiting for successful releases"
        max_times=${{ inputs.number-of-retries-to-wait-for-successful-deployment }}
        for app in "${apps[@]}"; do
          release_id=${apps_with_release_id[$app]}

          for i in $(seq 1 $max_times); do
            sleep 5
            if sos app:ps $app | grep -w -E "$release_id.*HEALTHY"; then break; fi
            echo "Continue waiting for $app release $release_id"

            if [ $i = $max_times ]; then exit 1; fi
          done
        done
      shell: bash
