name: "test-build-and-deployment-action"

on:
  push:
    branches: [main]
  pull_request:

env:
  SETOPS_ORG: ${{ secrets.SETOPS_ORG }}
  SETOPS_PROJECT: "githubactions"
  SETOPS_STAGE: "testing"
  SETOPS_APPS: "web worker"
  SETOPS_USERNAME: "github-actions-setup@setops.co"

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.build-and-push-image.outputs.image-tag }}
      stages-json: ${{ steps.build-and-push-image.outputs.stages-json }}
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Build image and push it to SetOps image registry"
        id: build-and-push-image
        uses: ./build-and-push-image
        with:
          setops-stages: ${{ env.SETOPS_STAGE }}
          setops-apps: ${{ env.SETOPS_APPS }}
          setops-username: ${{ env.SETOPS_USERNAME }}
          setops-password: ${{ secrets.SETOPS_PASSWORD }}
          setops-project: ${{ env.SETOPS_PROJECT }}
          setops-organization: ${{ env.SETOPS_ORG }}
          setops-version: v2.0.0-rc1
          build-context: ./.github/test-resources
          build-args: GIT_SHA=${{ github.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Setops Deployment
    strategy:
      fail-fast: false
      matrix:
        setops-stage: ${{ fromJson(needs.build.outputs.stages-json) }}
    concurrency: setops-deployment-${{ github.ref }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Deploy apps on SetOps"
        id: deploy
        uses: ./deployment
        with:
          setops-stage: ${{ matrix.setops-stage }}
          setops-apps: ${{ env.SETOPS_APPS }}
          setops-project: ${{ env.SETOPS_PROJECT }}
          setops-username: ${{ env.SETOPS_USERNAME }}
          setops-password: ${{ secrets.SETOPS_PASSWORD }}
          setops-version: v2.0.0-rc1
          image-tag: ${{ needs.build.outputs.image-tag }}
          setops-organization: ${{ env.SETOPS_ORG }}
          predeploy-command: echo "Hello World"
          predeploy-command-detach-timeout: 300s
          predeploy-command-cpu: 128
          predeploy-command-memory: 128
          github-token: ${{ secrets.GITHUB_TOKEN }}
