name: "test-setup-action-build"

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./setup

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install
        run: npm clean-install

      - name: Verify
        run: |
          npm run build
          # Fail if "npm run build" generated new changes in dist
          git update-index --refresh dist/* && git diff-index --quiet HEAD dist

      - name: Test
        run: npm test
